import { CanvasNode, CanvasEdge } from "@/types";

export const INITIAL_NODES: Record<string, CanvasNode> = {
  step1: {
    id: "step1",
    label: "Escopo",
    type: "input",
    data: { label: "Escopo em uma frase", content: "", description: "Defina em uma frase o produto, serviço ou solução que sua startup pretende criar." },
    position: { x: 400, y: 50 },
    completed: false,
    locked: false,
  },
  step2: {
    id: "step2",
    label: "Paradigma",
    type: "branching",
    data: { label: "Paradigma", choice: null, description: "Escolha o tipo de inovação: Novo Paradigma Tecnológico (inovação radical) ou Mudança de Paradigma (ruptura de modelo existente)." },
    position: { x: 400, y: 250 },
    completed: false,
    locked: true,
  },
  step2a: {
    id: "step2a",
    label: "Oceano de Oportunidades",
    type: "input",
    data: {
      label: "Oceano de Oportunidades",
      content: "",
      description: "Descreva o espaço de mercado inexplorado que sua inovação tecnológica irá ocupar.\n\n💡 Exemplo: 'Professores de redes públicas que precisam de planos de aula personalizados com IA, operando 100% offline em escolas sem conectividade estável.'",
    },
    position: { x: 100, y: 450 },
    completed: false,
    locked: true,
  },
  step2b: {
    id: "step2b",
    label: "Novo Modelo de Negócio",
    type: "input",
    data: {
      label: "Novo Modelo de Negócio",
      content: "",
      description: "Descreva como seu novo modelo de negócio rompe com o padrão atual do mercado.\n\n💡 Exemplo: 'Cobrança por aluno ativo via assinatura municipal, substituindo a compra tradicional de apostilas impressas.'",
    },
    position: { x: 700, y: 450 },
    completed: false,
    locked: true,
  },
  step3: {
    id: "step3",
    label: "Análise de Mercado",
    type: "market",
    data: {
      label: "Análise de Mercado",
      audience: "",
      inspiration: "",
      competitor: "",
      description: "Identifique quem é seu público-alvo e sua referência de mercado.\n\n💡 Exemplo Público-Alvo: 'Professores e gestores pedagógicos do ensino fundamental II de escolas públicas.'\n\n💡 Exemplo Inspiração/Concorrente: 'Khan Academy (na personalização do aprendizado) ou Google Classroom.'",
    },
    position: { x: 400, y: 650 },
    completed: false,
    locked: true,
  },
  step4: {
    id: "step4",
    label: "Dimensionamento (TAM/SAM/SOM)",
    type: "pyramid",
    data: { label: "Dimensionamento (TAM/SAM/SOM)", tam: "", sam: "", som: "", description: "TAM: todo o mercado disponível (100% dos potenciais clientes). SAM: a fatia que você consegue atingir com seu modelo atual. SOM: o que você pode conquistar realisticamente nos próximos 1–3 anos. Para cada um, descreva em uma frase, informe o tamanho estimado e cite a fonte dos dados." },
    position: { x: 400, y: 900 },
    completed: false,
    locked: true,
  },
  step5: {
    id: "step5",
    label: "Formatos e Monetização",
    type: "format",
    data: { label: "Formatos e Monetização", businessFormat: [], revenueFormats: [], description: "Defina como sua startup se posiciona (B2B, B2C etc.) e como vai gerar receita (SaaS, Assinatura, Freemium etc.)." },
    position: { x: 400, y: 1150 },
    completed: false,
    locked: true,
  },
  step6: {
    id: "step6",
    label: "Business Model Canvas",
    type: "bmc",
    data: {
      label: "Business Model Canvas",
      description: "Preencha os 9 blocos do BMC de Osterwalder para descrever como seu negócio cria, entrega e captura valor. São necessários pelo menos 5 campos.",
      keyPartners: "",
      keyActivities: "",
      keyResources: "",
      valueProposition: "",
      customerSegments: "",
      customerRelationships: "",
      channels: "",
      costStructure: "",
      revenueStreams: "",
    },
    position: { x: 50, y: 1450 },
    completed: false,
    locked: true,
  },
  step6_vpc: {
    id: "step6_vpc",
    label: "Value Proposition Canvas",
    type: "vpc",
    data: {
      label: "Value Proposition Canvas",
      description: "Detalha o encaixe entre sua Proposta de Valor e as necessidades do cliente. Preencha os dois lados: Proposta de Valor (esquerda) e Perfil do Cliente (direita). Mínimo 4 campos.",
      products: "",
      gainCreators: "",
      painRelievers: "",
      gains: "",
      customerJobs: "",
      pains: "",
    },
    position: { x: 1060, y: 1450 },
    completed: false,
    locked: true,
  },
  step6_merge: {
    id: "step6_merge",
    label: "Estratégia Unificada",
    type: "merger",
    data: { label: "Estratégia Unificada" },
    position: { x: 620, y: 2060 },
    completed: false,
    locked: true,
  },
  step7: {
    id: "step7",
    label: "Stack Tecnológica",
    type: "input",
    data: { label: "Stack Tecnológica", content: "", description: "Liste as tecnologias, plataformas e ferramentas que serão usadas para construir a solução." },
    position: { x: 620, y: 2300 },
    completed: false,
    locked: true,
  },
  step8: {
    id: "step8",
    label: "Protótipo Front-end",
    type: "input",
    data: { label: "Protótipo Front-end", content: "", description: "Descreva ou cole o link do protótipo visual da interface (Figma, wireframe etc.)." },
    position: { x: 620, y: 2550 },
    completed: false,
    locked: true,
  },
};

export const INITIAL_EDGES: CanvasEdge[] = [
  { id: "e1-2", source: "step1", target: "step2", animated: true },
  { id: "e2-2a", source: "step2", target: "step2a", animated: true },
  { id: "e2-2b", source: "step2", target: "step2b", animated: true },
  { id: "e2-3", source: "step2", target: "step3", animated: true },
  { id: "e3-4", source: "step3", target: "step4", animated: true },
  { id: "e4-5", source: "step4", target: "step5", animated: true },
  { id: "e5-6", source: "step5", target: "step6", animated: true },
  { id: "e5-6vpc", source: "step5", target: "step6_vpc", animated: true },
  { id: "e6-merge", source: "step6", target: "step6_merge", animated: true, targetHandle: "left" },
  { id: "e6vpc-merge", source: "step6_vpc", target: "step6_merge", animated: true, targetHandle: "right" },
  { id: "e6merge-7", source: "step6_merge", target: "step7", animated: true },
  { id: "e7-8", source: "step7", target: "step8", animated: true },
];

export const PARADIGM_OPTIONS = [
  {
    value: "A",
    label: "Novo Paradigma Tecnológico",
    description: "Inovação Radical/Disruptiva",
  },
  {
    value: "B",
    label: "Mudança de Paradigma",
    description: "Quebra/Ruptura do padrão atual",
  },
];

export const BUSINESS_FORMATS = [
  "B2B",
  "B2C",
  "B2B2C",
  "C2C",
  "D2C",
];

export const REVENUE_FORMATS = [
  "SaaS",
  "BaaS",
  "Pay-as-you-go",
  "Assinatura",
  "Freemium",
  "Venda Direta",
];
